### ISSUE TITLE
arrangeColumnsData() has to use the original column names

### ISSUE THREAD

**Issue by n0rbyt3** [AnatolyUss/FromMySqlToPostgreSql#43]
In ```arrangeColumnsData()``` a function is used for some special column types. These column names are used for select and re-used for the INSERT statements but functions are not valid column names.

The script will create false statements like:
INSERT INTO "public"."table" ("id","IF(`date_column` IN('0000-00-00', '0000-00-00 00:00:00'), '-INFINITY', `date_column`)"

Giving the functions an alias like the original column name, it will fix the issue.

**Comment by AnatolyUss** [comment]
Just removed the usage of INSERT statement.
There is no reason why INSERT should succeed if COPY failed.
BTW a massive usage of INSERTs will increase RAM consumption drastically.
Probably, your actual problem is that some chunk of data was rejected by PostgreSQL.

Try the latest version, run it, and when it finishes have a look at /logs_directory/all.log file.
If you'll find statements like:
"Following MySQL query will return a data set, rejected by PostgreSQL:"
then copy-paste the sql below this statement and run it. You will get the data-set rejected by PostgreSQL. You will see what kind of data led to the error...
