### ISSUE TITLE
How to install PD_MYSQL, PDO_PGSQL, etc... ?

### ISSUE THREAD

**Issue by omasseau** [AnatolyUss/FromMySqlToPostgreSql#77]
In the documentation you say:

PDO_MYSQL should be installed and enabled
PDO_PGSQL should be installed and enabled
mbstring should be installed and enabled
register_argc_argv should be enabled (check php.ini).
postgis should be installed and enabled to migrate spatial data (geometry type columns).

But how do I install this after installing the PHP CLI ?

PS: I'm on Windows and I don't know anything about PHP  :)

Quote: _Ease of use - the only thing needed to run this script is the PHP(CLI) interpreter._

**Comment by AnatolyFromPerion** [comment]
Hello,
Well, back in 2015, I guess PHP was bundled with PDO_... stuff, so the only step to do was enabling required extensions in php.ini  )))

Following wouldn't answer your questions, it's just a suggestion:
1. Git-clone [Nmig](https://github.com/AnatolyUss/nmig) .
2. Install [Node.js](https://nodejs.org/en/) , which is quite easy, since they provide Windows installer.
3. Just follow the instructions on Nmig's page (you'll need to run 3 simple commands along the way; commands are provided).

In general, Nmig is way simpler to install/configure than PHP, and Nmig is faster.

**Comment by omasseau** [comment]
Hello,

Ah thanks.
Indeed I see 2 files in the php root folder: php.ini-development and php.ini-production.

I renamed php.ini-development to php.ini and uncommented:

extension=mbstring
extension=pdo_mysql
extension=pdo_pgsql
extension=pgsql
extension_dir="ext"
register_argc_argv

Now everything works ;)

Will give a try to Nmig later (Cannot install node.js at the moment because of some admin rights problems).
